dashboard:
  path: /
  controller: \Pos\Controller\DashboardController::main

transactions_list:
  path: /produse
  controller: \Pos\Controller\TransactionController::list

print_months:
  path: /print
  controller: \Pos\Controller\TransactionController::printMonths

order_new:
  path: /order/new
  controller: \Pos\Controller\OrderController::new
order_edit:
  path: /order/{order}/edit
  controller: \Pos\Controller\OrderController::edit
  requirements:
    order: '\d+'
order_delete:
  path: /order/{order}/delete
  controller: \Pos\Controller\OrderController::delete
  requirements:
    order: '\d+'

transaction_drives:
  path: /drives
  controller: \Pos\Controller\TransactionController::showDrives

sale_new:
  path: /sale/new
  controller: \Pos\Controller\SaleController::new
sale_edit:
  path: /sale/{sale}/edit
  controller: \Pos\Controller\SaleController::edit
  requirements:
    sale: '\d+'
sale_delete:
  path: /sale/{sale}/delete
  controller: \Pos\Controller\SaleController::delete
  requirements:
    sale: '\d+'

register_show:
  path: /register
  controller: \Pos\Controller\RegisterController::show

register_product_list:
  path: /register/products
  controller: \Pos\Controller\Register\ProductController::list
register_product_new:
  path: /register/products/new
  controller: \Pos\Controller\Register\ProductController::new
register_product_edit:
  path: /register/products/{product}
  controller: \Pos\Controller\Register\ProductController::edit
  requirements:
    product: '\d+'
register_product_delete:
  path: /register/products/{product}/delete
  controller: \Pos\Controller\Register\ProductController::delete
  requirements:
    order: '\d+'

register_product_category_list:
  path: /register/product/categories
  controller: \Pos\Controller\Register\CategoryController::list
register_product_category_new:
  path: /register/product/categories/new
  controller: \Pos\Controller\Register\CategoryController::new
register_product_category_edit:
  path: /register/product/categories/{category}
  controller: \Pos\Controller\Register\CategoryController::edit
  requirements:
    category: '\d+'
register_product_category_delete:
  path: /register/product/categories/{category}/delete
  controller: \Pos\Controller\Register\CategoryController::delete
  requirements:
    category: '\d+'