dashboard:
  path: /
  controller: \Pos\Controller\DashboardController::main

transactions_list:
  path: /produse
  controller: \Pos\Controller\TransactionController::list

print_months:
  path: /print
  controller: \Pos\Controller\TransactionController::printMonths

order_new:
  path: /order/new
  controller: \Pos\Controller\OrderController::new
order_edit:
  path: /order/{order}/edit
  controller: \Pos\Controller\OrderController::edit
  requirements:
    order: '\d+'
order_delete:
  path: /order/{order}/delete
  controller: \Pos\Controller\OrderController::delete
  requirements:
    order: '\d+'

transaction_drives:
  path: /drives
  controller: \Pos\Controller\TransactionController::showDrives

sale_new:
  path: /sale/new
  controller: \Pos\Controller\SaleController::new
sale_edit:
  path: /sale/{sale}/edit
  controller: \Pos\Controller\SaleController::edit
  requirements:
    sale: '\d+'
sale_delete:
  path: /sale/{sale}/delete
  controller: \Pos\Controller\SaleController::delete
  requirements:
    sale: '\d+'